// All 6 artist profiles. Each has dossier cards, a question bank, fraud tells, and feedback lines.
const ARTISTS = [
  {
    id: 'vangogh',
    displayName: 'Vincent van Gogh',
    portrait: 'V',
    portraitColor: '#e8c547',

    bio:        'Dutch painter, 1853–1890. Struggled with mental illness his whole life and only sold ONE painting while alive.',
    style:      'Post-Impressionism — thick swirling brushstrokes that show how he FELT, not just what he saw.',
    technique:  'Impasto — squeezed paint straight from the tube and applied it so thick the strokes rise from the canvas in 3D.',
    palette:    ['vivid yellow', 'deep blue', 'bright orange'],
    famousWork: { title: 'The Starry Night', year: 1889, note: 'Swirling night sky over a sleeping village — painted from his asylum bedroom window.' },
    message:    'Emotions are more real than appearances. Art should make you feel, not just see.',
    quirk:      'Signed every painting with only his first name — just "Vincent" — never his last name.',

    questions: [
      { id: 'q_tech',    text: 'How do you apply your paint — what makes your technique special?',  value: 'high',
        trueAnswer: 'I squeeze paint straight from the tube — thick, heavy impasto. The brushstrokes stand up from the canvas in 3D. You can feel the texture if you run your finger over it.' },
      { id: 'q_palette', text: 'What colours are you most famous for?',                              value: 'high',
        trueAnswer: 'Vivid yellow, deep blue, and bright orange. Yellow especially — it feels like warmth and life to me.' },
      { id: 'q_quirk',   text: 'How do you sign your paintings?',                                   value: 'high',
        trueAnswer: 'Just "Vincent." Never my last name. Van Gogh is too hard for people to pronounce, and Vincent feels more honest.' },
      { id: 'q_work',    text: 'Tell me about your most famous painting.',                           value: 'high',
        trueAnswer: '"The Starry Night," 1889. I painted it from my window at the Saint-Paul asylum. All those swirling spirals — the sky felt alive to me that night.' },
      { id: 'q_style',   text: 'How would you describe your art style?',                             value: 'high',
        trueAnswer: 'Post-Impressionism. I start with what I see, but exaggerate colour and shape to show how I feel. The swirling lines are my emotions, not just the sky.' },
      { id: 'q_feel',    text: 'Do you enjoy being an artist?',                                     value: 'low',
        trueAnswer: 'It is the only thing that keeps me sane — or tries to. When I paint I forget the darkness for a while.' },
      { id: 'q_bio',     text: 'Have you been commercially successful?',                            value: 'low',
        trueAnswer: 'Not at all. I have sold only one painting in my life. But I paint because I must, not for money.' },
    ],

    fraudTells: [
      { questionId: 'q_quirk',
        fraudAnswer: 'I sign them "V. van Gogh" — full initials and last name. I like it to look official and complete.' },
      { questionId: 'q_work',
        fraudAnswer: '"The Starry Night," which I painted in 1885 — during my time in Arles, looking out over the Rhône.' },
      { questionId: 'q_palette',
        fraudAnswer: 'Deep green, muted purple, and burnt sienna — earthy tones. I wanted my paintings to feel grounded and natural.' },
    ],

    feedback: {
      caughtTell:  'Sharp! The file says he signed only "Vincent" — this person said "V. van Gogh." Real tells hide in small details.',
      missedTell:  'Hint: re-read the Quirk card. Van Gogh\'s signature was very unusual — and this person described the opposite.',
      realCorrect: 'Authenticated! Citing the impasto technique (thick paint, 3D texture) was spot-on evidence.',
      falseAccuse: 'Careful — everything this person said matched the file. The signature, colours, and date were all correct.',
    },
  },

  {
    id: 'kahlo',
    displayName: 'Frida Kahlo',
    portrait: 'F',
    portraitColor: '#c0392b',

    bio:        'Mexican painter, 1907–1954. Survived a devastating bus accident at 18 that broke her spine and left her in pain for life — and turned her to painting.',
    style:      'Surrealism mixed with Mexican folk art — dreamlike, deeply personal, and full of Mexican symbols.',
    technique:  'Tiny, incredibly detailed brushwork — every eyelash, every petal, every thread of fabric painted with near-microscopic care.',
    palette:    ['bright red', 'deep teal', 'warm gold'],
    famousWork: { title: 'The Two Fridas', year: 1939, note: 'Two versions of herself sitting together — hearts connected by a thin vein, one whole, one cut open.' },
    message:    'Pain, identity, and Mexican culture are things to show with pride, not hide. Art is the most honest way to tell your own story.',
    quirk:      'Always portrayed her unibrow and faint facial hair exactly as they were — she never "corrected" her face in any portrait.',

    questions: [
      { id: 'q_tech',    text: 'What is special about the fineness of your brushwork?',             value: 'high',
        trueAnswer: 'I paint in tiny, meticulous detail — every hair, every petal is precise. I learned to look this closely during my long recovery when I was bedridden and could only reach a small canvas.' },
      { id: 'q_palette', text: 'Which colours appear most in your work?',                           value: 'high',
        trueAnswer: 'Bright red, deep teal, and warm gold — Mexican colours, loud and alive.' },
      { id: 'q_quirk',   text: 'How do you portray your own face in self-portraits?',               value: 'high',
        trueAnswer: 'Exactly as I look — unibrow, faint moustache and all. I refuse to smooth it away. My face is mine and I am proud of it.' },
      { id: 'q_work',    text: 'Tell me about The Two Fridas.',                                     value: 'high',
        trueAnswer: '"The Two Fridas," 1939 — the year I divorced Diego Rivera. Two versions of me, hearts joined by a vein. One heart is whole; one is cut open and bleeding.' },
      { id: 'q_style',   text: 'What art movement are you associated with?',                        value: 'high',
        trueAnswer: 'Surrealism mixed with Mexican folk art — though I always said I don\'t paint dreams, I paint my own reality. And my reality was stranger than any dream.' },
      { id: 'q_feel',    text: 'Why did you start painting?',                                       value: 'low',
        trueAnswer: 'The bus accident. I was bedridden for months. My mother had a mirror placed above my bed and I started painting myself — it was the only subject I could reach.' },
      { id: 'q_bio',     text: 'What hardship most shaped your art?',                               value: 'low',
        trueAnswer: 'The accident at 18. Broken spine, collarbone, ribs, leg. More than 35 surgeries in my life. That pain is in every painting.' },
    ],

    fraudTells: [
      { questionId: 'q_quirk',
        fraudAnswer: 'In self-portraits I always softened my brows and cleared my skin a little — art is about showing your best self, not every imperfection.' },
      { questionId: 'q_work',
        fraudAnswer: '"The Two Fridas," painted in 1928 — early in my career, before I had met Diego Rivera.' },
      { questionId: 'q_palette',
        fraudAnswer: 'Soft pastels — pale pink, lavender, and cream. Mexican colours can be very gentle and subtle.' },
    ],

    feedback: {
      caughtTell:  'Excellent! The file says Kahlo always showed her unibrow exactly as it was — this forger described the opposite. That contradicts everything she stood for.',
      missedTell:  'Tip: re-read the Quirk card. Kahlo\'s attitude toward her own face was very specific — and this person described the exact opposite.',
      realCorrect: 'Great authentication! Noting the tiny detailed brushwork matches the Technique card exactly.',
      falseAccuse: 'Everything matched — the face quirk, 1939, and the correct bright colours. No fraud here.',
    },
  },

  {
    id: 'monet',
    displayName: 'Claude Monet',
    portrait: 'M',
    portraitColor: '#8e44ad',

    bio:        'French painter, 1840–1926. Kept painting even as he went nearly blind in old age — his final Water Lilies were made when he could barely see.',
    style:      'Impressionism — capturing a single moment of light and atmosphere rather than sharp, precise detail.',
    technique:  'Short, separate dabs of pure colour placed side by side. Up close they look like chaos; from a distance they blur into shimmering light.',
    palette:    ['soft violet', 'pale green', 'warm gold'],
    famousWork: { title: 'Water Lilies', year: 1906, note: 'A series of 250+ paintings of his garden pond at Giverny — the same scene in different light and seasons.' },
    message:    'A single moment of light is worth capturing forever. The world is always changing, so painting is the only way to hold a moment still.',
    quirk:      'Always painted standing up — he refused to sit while working, even when almost completely blind.',

    questions: [
      { id: 'q_tech',    text: 'How do you create those shimmering, glowing effects?',              value: 'high',
        trueAnswer: 'Short separate dabs of pure colour — never blended on the palette. Up close it looks like dots of chaos. Step back and your eye blends it into glowing, vibrating light.' },
      { id: 'q_palette', text: 'What colours define your work?',                                    value: 'high',
        trueAnswer: 'Soft violet, pale green, and warm gold — the colours of water and reflected light.' },
      { id: 'q_quirk',   text: 'Do you have any unusual habits while working?',                     value: 'high',
        trueAnswer: 'I always paint standing up. Always. Even now that my sight is almost gone — I know my garden by feel and I work on my feet.' },
      { id: 'q_work',    text: 'Tell me about the Water Lilies series.',                            value: 'high',
        trueAnswer: 'Over 250 paintings of the pond at my Giverny garden. I began around 1896 and kept going until I died — the same pond, a thousand different moments of light.' },
      { id: 'q_style',   text: 'You started a whole art movement — what is it?',                   value: 'high',
        trueAnswer: 'Impressionism. The name came from a critic mocking my painting "Impression, Sunrise." I decided to keep the name — it fit perfectly.' },
      { id: 'q_feel',    text: 'What inspires you most?',                                           value: 'low',
        trueAnswer: 'Light. How it transforms everything. The same lily pond at dawn is completely different by noon or dusk. I want to catch all of them.' },
      { id: 'q_bio',     text: 'How did you keep painting with failing eyesight?',                  value: 'low',
        trueAnswer: 'I knew my garden so well I could paint from memory and feel. I also had cataract surgery late in life, which helped somewhat.' },
    ],

    fraudTells: [
      { questionId: 'q_quirk',
        fraudAnswer: 'I always paint sitting down on a low stool — it keeps me at eye level with the water and lily pads. Very important for getting the perspective right.' },
      { questionId: 'q_work',
        fraudAnswer: 'The Water Lilies series — I started those paintings in 1920, a late-career project in the final years of my life.' },
      { questionId: 'q_palette',
        fraudAnswer: 'Bold cobalt blue, crimson, and pure white. I liked strong contrasts — colours that pop and vibrate against each other.' },
    ],

    feedback: {
      caughtTell:  'Good catch! The file clearly states Monet always painted STANDING — this person said they sit on a stool. Habits are hard to fake.',
      missedTell:  'Look at the Quirk card — Monet\'s posture while painting was unusual, and this person described the exact opposite.',
      realCorrect: 'Well done! The separate dabs of colour technique is the heart of Impressionism — excellent evidence.',
      falseAccuse: 'Everything this person said checked out. The standing habit, dates, and soft violet/pale green palette all matched.',
    },
  },

  {
    id: 'picasso',
    displayName: 'Pablo Picasso',
    portrait: 'P',
    portraitColor: '#2c3e50',

    bio:        'Spanish painter, 1881–1973. One of the most famous artists of the 20th century, known for reinventing art multiple times across a very long career.',
    style:      'Cubism — breaking objects and faces into geometric shapes and showing multiple viewpoints at the same time.',
    technique:  'Collage — the first major artist to glue newspaper clippings, fabric, and found objects directly onto canvas as part of the painting.',
    palette:    ['grey', 'brown', 'black'],
    famousWork: { title: 'Guernica', year: 1937, note: 'A huge black-and-white painting (~3.5m tall) depicting the Nazi bombing of the Spanish town of Guernica.' },
    message:    'Art should shock you into feeling something real. Comfortable, pretty art is useless — it must disturb, challenge, or anger you.',
    quirk:      'Always kept a large, messy collection of strange objects — bones, hats, masks, toys, newspapers — that secretly appear hidden in his paintings.',

    questions: [
      { id: 'q_tech',    text: 'You invented a major new technique — what is it?',                  value: 'high',
        trueAnswer: 'Collage — I was the first to paste real materials onto a painting. Newspaper, fabric, rope, anything nearby. Art doesn\'t have to be only paint.' },
      { id: 'q_palette', text: 'What colours do you use most in your Cubist work?',                 value: 'high',
        trueAnswer: 'Grey, brown, and black — especially in Cubist paintings. I wanted structure and form, not decoration. Too much colour distracts from the geometry.' },
      { id: 'q_quirk',   text: 'Tell me about your studio and what you keep in it.',                value: 'high',
        trueAnswer: 'It is a wonderful mess — bones, old masks, hats, newspapers, toys all piled up. They find their way into the paintings, hidden if you look carefully.' },
      { id: 'q_work',    text: 'Tell me about Guernica.',                                           value: 'high',
        trueAnswer: '"Guernica," 1937 — my response to the Nazi bombing of that Basque town. Nearly 3.5 metres tall, all black and white and grey. No colour — colour would have made it pretty, and it needed to be brutal.' },
      { id: 'q_style',   text: 'What is Cubism?',                                                   value: 'high',
        trueAnswer: 'Breaking everything into geometric pieces and showing multiple angles at once — the front and side of a face simultaneously. Reality is not one fixed viewpoint.' },
      { id: 'q_feel',    text: 'Are you satisfied being so famous?',                                value: 'low',
        trueAnswer: 'Fame is fine. But I care about work that lasts. Comfort is the enemy of real art.' },
      { id: 'q_bio',     text: 'Where are you originally from?',                                    value: 'low',
        trueAnswer: 'Málaga, Spain. But I spent most of my life in France. I never returned to Spain while Franco was in power.' },
    ],

    fraudTells: [
      { questionId: 'q_quirk',
        fraudAnswer: 'I keep a very tidy studio — clear surfaces, organised shelves. I believe a clean workspace creates clear thinking. Clutter distracts me.' },
      { questionId: 'q_work',
        fraudAnswer: '"Guernica" — I painted it in 1932, my response to the rising political tensions in Spain at the time.' },
      { questionId: 'q_palette',
        fraudAnswer: 'Bold primary colours — red, yellow, and blue. Cubism needs strong colour to make the geometry clear and readable.' },
    ],

    feedback: {
      caughtTell:  'Great detective work! The file says Picasso\'s studio was famously CLUTTERED with strange objects — this person claimed to be tidy. Complete contradiction.',
      missedTell:  'Check the Quirk card — Picasso\'s studio habits were unusual, and this person described the exact opposite.',
      realCorrect: 'Spot on! The collage technique as Picasso\'s innovation is exactly right — solid authentication.',
      falseAccuse: 'This person\'s answers all matched the file. The messy studio, 1937, and grey/brown/black palette were all correct.',
    },
  },

  {
    id: 'okeeffe',
    displayName: "Georgia O'Keeffe",
    portrait: 'G',
    portraitColor: '#c0392b',

    bio:        "American painter, 1887–1986. Moved to the New Mexico desert in 1949 and lived there alone, finding beauty in bones and vast emptiness.",
    style:      "American Modernism — simplified, enlarged shapes that turn ordinary objects into almost-abstract forms.",
    technique:  "Painted ordinary objects enormously large — a single flower fills the entire canvas so you cannot look away or miss it.",
    palette:    ['desert red', 'bone white', 'sage green'],
    famousWork: { title: 'Black Iris', year: 1926, note: 'A dark iris painted so large and up-close it looks like an abstract landscape rather than a flower.' },
    message:    "If you look at anything long enough, it becomes extraordinary. Slowing down and truly SEEING is what art is for.",
    quirk:      "Always included at least one animal skull or bone somewhere in her desert paintings — she collected them from the desert floor.",

    questions: [
      { id: 'q_tech',    text: 'What makes your painting technique instantly recognisable?',        value: 'high',
        trueAnswer: 'I make things enormous — one flower fills the whole canvas. You can\'t glance at it and walk away. You are forced to really look.' },
      { id: 'q_palette', text: 'What colours are you known for?',                                   value: 'high',
        trueAnswer: 'Desert red, bone white, and sage green — the colours of New Mexico. The earth, the sky, the bleached bones on the ground.' },
      { id: 'q_quirk',   text: 'Is there something you include in nearly all your desert paintings?', value: 'high',
        trueAnswer: 'Animal skulls and bones — I collect them from the desert floor, and they appear in almost every landscape I paint. I find them beautiful, not morbid.' },
      { id: 'q_work',    text: 'Tell me about Black Iris.',                                         value: 'high',
        trueAnswer: '"Black Iris," 1926 — a dark purple iris so close and so large it stops looking like a flower and starts looking like an abstract landscape. It forces you to see something you\'d normally just walk past.' },
      { id: 'q_style',   text: 'How would you describe your style?',                                value: 'high',
        trueAnswer: 'American Modernism — I simplified shapes down to their essential form. No clutter, just the object itself, made large enough to demand your full attention.' },
      { id: 'q_feel',    text: 'Why did you move to the desert?',                                   value: 'low',
        trueAnswer: 'I needed silence and space. New Mexico gave me both. The bones, the red earth, the enormous sky — nothing stands between you and the world there.' },
      { id: 'q_bio',     text: 'Tell me about your later life.',                                    value: 'low',
        trueAnswer: 'I moved permanently to Ghost Ranch, New Mexico in 1949 and lived there alone — very simply, painting, walking, tending my garden. I lived to 98.' },
    ],

    fraudTells: [
      { questionId: 'q_quirk',
        fraudAnswer: 'I include a small blue butterfly somewhere in most of my paintings — it\'s my private signature, a symbol of transformation and new life.' },
      { questionId: 'q_work',
        fraudAnswer: '"Black Iris," painted in 1934 — one of my New Mexico paintings inspired by the desert wildflowers.' },
      { questionId: 'q_palette',
        fraudAnswer: 'Ocean blue, sandy yellow, and deep forest green — I was inspired by the coastline before I moved to the desert.' },
    ],

    feedback: {
      caughtTell:  "Good eye! The file says O'Keeffe includes animal skulls and bones — this person mentioned a butterfly. That is not in any O'Keeffe file anywhere.",
      missedTell:  "Re-read the Quirk card — O'Keeffe had a very specific recurring element in her desert paintings, and this person named something completely different.",
      realCorrect: "Excellent! The enlarged ordinary-objects technique is O'Keeffe's defining method — strong evidence.",
      falseAccuse: "All answers matched the file. The skull habit, 1926, and desert red/bone white/sage green palette were all confirmed.",
    },
  },

  {
    id: 'davinci',
    displayName: 'Leonardo da Vinci',
    portrait: 'L',
    portraitColor: '#7f6000',

    bio:        'Italian Renaissance artist, 1452–1519. Also an inventor, scientist, engineer, and anatomist — he filled thousands of notebook pages with ideas, diagrams, and studies.',
    style:      'Renaissance — realistic, detailed, perfectly balanced, and harmonious. Everything in its right place.',
    technique:  'Sfumato — blending paint so softly there are no hard edges, only gradual transitions. Like looking through a thin haze of smoke.',
    palette:    ['warm brown', 'soft gold', 'deep shadow'],
    famousWork: { title: 'Mona Lisa', year: 1503, note: 'Portrait of a woman with a mysterious half-smile — the most visited painting in the world.' },
    message:    "Art and science are two ways of understanding the same world. You can't fully know one without the other.",
    quirk:      "Wrote all his personal notes and journals in backwards mirror-writing — you can only read them by holding a mirror to the page.",

    questions: [
      { id: 'q_tech',    text: 'What is sfumato and why did you develop it?',                      value: 'high',
        trueAnswer: 'Sfumato means "smoke" in Italian. I blend paint so gradually — tiny brush, infinite patience — until there are no hard lines anywhere. Every edge dissolves into the next tone like smoke or mist.' },
      { id: 'q_palette', text: 'What colours do you use most often?',                              value: 'high',
        trueAnswer: 'Warm browns, soft golds, and deep shadows — the colours of old stone and candlelight. I want figures to feel solid and three-dimensional.' },
      { id: 'q_quirk',   text: 'You have a very unusual way of writing your notes — can you describe it?', value: 'high',
        trueAnswer: 'I write backwards — mirror-writing, starting from the right side of the page moving left. Hold it to a mirror and it reads normally. I have always done it this way.' },
      { id: 'q_work',    text: 'Tell me about the Mona Lisa.',                                     value: 'high',
        trueAnswer: 'I began the Mona Lisa in 1503 and kept it with me for years — I never considered it finished. The smile took the longest. Sfumato makes it shift depending on where exactly you look.' },
      { id: 'q_style',   text: 'What art movement do you belong to?',                              value: 'high',
        trueAnswer: 'The Renaissance — a rebirth of classical knowledge and realistic art. We studied anatomy, mathematics, and nature to make art that truly reflects reality.' },
      { id: 'q_feel',    text: 'What do you do besides painting?',                                 value: 'low',
        trueAnswer: 'I design flying machines, study the human body through dissection, map rivers, investigate fossils, design weapons. Painting is one thread. Curiosity is the whole cloth.' },
      { id: 'q_bio',     text: 'Where did you spend most of your working life?',                   value: 'low',
        trueAnswer: 'Milan mostly, then Florence, then Rome, and finally France — King Francis I invited me to live at Château du Clos Lucé, where I died in 1519.' },
    ],

    fraudTells: [
      { questionId: 'q_quirk',
        fraudAnswer: 'I write in a personal cipher — a letter-substitution code that scrambles the alphabet. Only I and a few trusted assistants knew how to decode it.' },
      { questionId: 'q_work',
        fraudAnswer: 'The Mona Lisa — I painted her quickly in 1488. It was a straightforward commission that I completed in a few months.' },
      { questionId: 'q_palette',
        fraudAnswer: 'Vivid blue, bright vermillion red, and pure white — I believed strong contrasting colour made a painting come alive and grab attention.' },
    ],

    feedback: {
      caughtTell:  'Sharp! The file says da Vinci wrote in BACKWARDS mirror-writing. This person described a cipher code — a completely different thing.',
      missedTell:  'Go back to the Quirk card — da Vinci\'s writing method is famous and very specific. The forger substituted something different.',
      realCorrect: 'Excellent authentication! Citing sfumato (soft blended edges, no hard lines) is exactly right.',
      falseAccuse: 'All answers matched the dossier. The mirror-writing, 1503, and warm browns/golds palette were all confirmed. This was genuine.',
    },
  },
];
